version: '3.8'

services:
  transit-filter-api:
    container_name: transit-filter-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:${PORT:-3000}:3000"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://0.0.0.0:3000/v1/models"]
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
